config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'events/personal', to: 'events#personal', as: :personal_current
  get 'events/personal/:state', to: 'events#personal', as: :personal
  resources :events, except: [:show]

  get 'rooms/admin_index', to: 'rooms#admin_index', as: :admin_index
  get 'rooms/print/:id', to: 'rooms#show_print', as: :print
  resources :rooms

  root to: 'rooms#index'
end

app/models/event.rb
class Event < ApplicationRecord
  include DateValidators
  include ActiveModel::Validations

  belongs_to :room
  belongs_to :user
  belongs_to :organizer
  belongs_to :lector

  # проверка на присутствие
  validates :title,  :date, :begin_time, :end_time, :user_id, :organizer_id, :lector_id, :room_id, presence: true
  # проверка на integer и not_null
  validates :user_id, :organizer_id, :lector_id, :room_id, numericality: { only_integer: true }

  validates_with EventValidator

  def self.current_events(user_id)
    dtc = DateTime.current
    self.where(archive: false, user_id: user_id).where("date > ? or (date = ? and end_time > ?)",
      I18n.l(dtc, format: :date_db), I18n.l(dtc, format: :date_db), I18n.l(dtc)).order(:date).order(:begin_time)
  end

  def self.past_events(user_id)
    dtc = DateTime.current
    self.where(archive: false, user_id: user_id).where("date < ? or (date = ? and end_time <= ?)",
      I18n.l(dtc, format: :date_db), I18n.l(dtc, format: :date_db), I18n.l(dtc)).order(:date).reverse_order.order(:begin_time)
  end

  def self.canceled_events(user_id)
    self.where(archive: true, user_id: user_id).order(:date).reverse_order.order(:begin_time)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @events = Event.where(room_id: params[:room_id], archive: false).order(:begin_time)
  end

  def personal
    case params[:state]
    when 'past'
      @past = 'active'
      @current = @canceled = nil
      @events = Event.past_events(current_user.id)
    when 'canceled'
      @canceled = 'active'
      @current = @past = nil
      @events = Event.canceled_events(current_user.id)
    else
      @current = 'active'
      @past = @canceled = nil
      @events = Event.current_events(current_user.id)
    end
  end

  def new
    @event = Event.new
    @event.room_id = params[:room_id]
    @event.date = params[:date] ? params[:date] : Date.today
    @event.begin_time = Time.parse("12:00")
    @event.end_time = Time.parse("12:30")
    @rooms = Room.all
    flash[:notice] = ""

    respond_to do |format|
      format.html { render partial: 'new' }
    end
  end

  def create
    @event = Event.new(event_params)
    @rooms = Room.all
    respond_to do |format|
      if @event.save
        create_repeatly_events if params.permit(:repeatly).has_key? :repeatly

        format.html { redirect_to request.referrer }
      else
        flash[:notice] = @event.errors['text'].last
        format.html { render partial: 'new' }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @rooms = Room.all
    flash[:notice] = ""
    if Event.where("title = ? and id != ?", @event.title, @event.id).length != 0
      @repeatly = true
    else
      @repeatly = false
    end

    respond_to do |format|
      format.html { render partial: 'edit' }
    end
  end

  def update
    @event = Event.find(params[:id])
    @rooms = Room.all
    if Event.where("title = ? and id != ?", @event.title, @event.id).length != 0
      @repeatly = true
    else
      @repeatly = false
    end

    old_title = @event.title

    respond_to do |format|
      if @event.update(event_params)
        edit_repeatly_events(old_title) if params.permit(:change)[:change] == "future"
        create_repeatly_events if params.permit(:repeatly).has_key? :repeatly

        format.html { redirect_to request.referrer }
      else
        flash[:notice] = @event.errors['text'].last
        format.html { render partial: 'edit' }
      end
    end
  end

  def destroy
    deleting_event = Event.find(params[:id])
    case params.permit(:value)[:value]
    when "this"
      deleting_event.update(archive: true)
    when "future"
      deleting = Event.where("title = ? and room_id = ? and archive = ? and date >= ?", deleting_event.title, deleting_event.room_id, false, deleting_event.date)
    when "all"
      deleting = Event.where("title = ? and room_id = ? and archive = ?", deleting_event.title, deleting_event.room_id, false)
    end

    if deleting
      deleting.each do |event|
        event.update(archive: true)
      end
    end

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private def event_params
    params.require(:event).permit(:title, :description, :date, :room_id, :user_id).merge(event_time_params).merge(organizer_and_lector_params)
  end

  private def event_time_params
    {
      begin_time: Time.parse(params.require(:event).permit(:begin_time)[:begin_time]),
      end_time: Time.parse(params.require(:event).permit(:end_time)[:end_time])
    }
  end

  private def organizer_and_lector_params
    par = params.require(:event).permit(:organizer_id, :lector_id)

    org = if par[:organizer_id] == "0"
      Organizer.find_or_create_by(name: params.permit(:new_organizer)[:new_organizer]).id
    else
      par[:organizer_id]
    end

    lec = if par[:lector_id] == "0"
      Lector.find_or_create_by(name: params.permit(:new_lector)[:new_lector]).id
    else
      par[:lector_id]
    end
    
    {
      organizer_id: org,
      lector_id: lec
    }
  end

  private def check_user
    unless current_user.role == "admin" || current_user.id == Event.find(params[:id]).user_id
      redirect_to "users/sign_in", :status => 401
    end
  end

  private def create_repeatly_events
    case params.permit(:period)[:period]
    when "Каждый день"
      period = 1.day
    when "Каждую неделю"
      period = 7.days
    when "Каждый месяц"
      period = 1.month
    end

    date = DateTime.parse(event_params[:date]) + period
    max_date = Date.parse(params.permit(:max_date)[:max_date])

    while date <= max_date
      e = Event.new(event_params)
      e.date = date
      e.save
      date += period
    end
  end

  private def edit_repeatly_events (old_title)
    Event.where("title = ? and room_id = ? and date > ?", old_title, @event.room_id, @event.date).each do |editable_event|
      editable_event.update(@event.attributes.except("id", "date"))
    end
  end

  private def assist
    respond_to do |format|
      format.html do
        render partial: 'events/assist', locals: { room: Room.find(params[:room_id]) }
      end
    end
  end

end

app/views/events/_button_group.html.slim
.envents-header
  a.btn.btn-success.for_new style="float: right;" =t('events.btn_create')
  .btn-group.user_menu
    = link_to t('events.btn_current'), personal_current_path, class: "btn btn-primary #{current}"
    = link_to t('events.btn_past'), personal_path('past'), class: "btn btn-primary #{past}"
    = link_to t('events.btn_canceled'), personal_path('canceled'), class: "btn btn-primary #{canceled}"

app/views/events/_edit.html.slim
= form_for :event, url: event_path(@event), method: :patch, remote: true do |f|
  -if @repeatly
    p
      = label_tag t('events.btn_delete')
      .btn-group
        = link_to t('events.btn_all'), event_path(id: @event.id, value:"all"), method: :delete, data: { confirm: t('events.alert.delete_chain_of_events') }, class: "btn btn-danger removing"
        = link_to t('events.btn_this'), event_path(id: @event.id, value:"this"), method: :delete, data: { confirm: t('events.alert.delete_this_event') }, class: "btn btn-danger removing"
        = link_to t('events.btn_future'), event_path(id: @event.id, value:"future"), method: :delete, data: { confirm: t('events.alert.delete_chain_of_events') }, class: "btn btn-danger removing"
    hr
    p
      = label_tag t('events.btn_change')
      .btn-group data-toggle="buttons"
        =label_tag :change_this, class: "btn btn-primary active"
          = radio_button_tag :change, "this"
          =t('events.btn_this')
        =label_tag :change_future, class: "btn btn-primary"
          = radio_button_tag :change, "future"
          =t('events.btn_future')
  -else
    p
      .btn-group
        = link_to t('events.btn_this'), event_path(id: @event.id, value:"this"), method: :delete, data: { confirm: t('events.alert.delete_this_event') }, class: "btn btn-danger removing"
  hr
  = render partial: 'events/form', locals: { f: f, repeat_label: t('events.form.repeat_label_for_edit') }

app/views/events/_form.html.slim
-if flash[:notice]
  .notice
    -if flash[:notice] == 'Длительность < 15 минут'
      =t('events.form.form_error.wrong_event_time')
    -if flash[:notice] == 'Мимо комнаты'
      =t('events.form.form_error.conflux_with_room_time')
    -if flash[:notice] == 'Пересечение событий'
      =t('events.form.form_error.conflux_events')
br

.row
  div.col-sm-12
    = f.label :title, t('events.title')
    = f.text_field :title, :class => "form-control"
br

div
  = f.label :description, t('events.description')
  = f.text_area :description, :class => "form-control"
br

.row
  div.col-sm-4
    = f.label :date, t('events.date')
    = f.text_field :date, value: l(@event.date), :class => "form-control for_date", id: "datetimepicker1"
  div.col-sm-4
    = f.label :begin_time, t('events.form.begin_time')
    = f.text_field :begin_time, value: l(@event.begin_time.localtime), :class => "form-control for_time", :id => 'datetimepicker2'
  div.col-sm-4
    = f.label :end_time, t('events.form.end_time')
    = f.text_field :end_time, value: l(@event.end_time.localtime), :class => "form-control for_time", :id => 'datetimepicker3'
br

.row
  div.col-sm-6
    = f.label :organizer_id, t('events.organizer')
    = f.select :organizer_id, options_for_select(Organizer.all.map{ |organizer| [organizer.name, organizer.id] }.push(["добавить", 0]), @event.organizer_id), {}, class: "form-control"
    = text_field_tag :new_organizer, "", :class => "form-control hideble"
  div.col-sm-6
    = f.label :lector_id, t('events.lector')
    = f.select :lector_id, options_for_select(Lector.all.map{ |lector| [lector.name, lector.id] }.push(["добавить", 0]), @event.lector_id), {}, class: "form-control"
    = text_field_tag :new_lector, "", :class => "form-control hideble"

- u_i = if @event.user_id? then @event.user_id else current_user.id end
= f.hidden_field :user_id, value: u_i, as: :hidden

hr

label
  = check_box_tag :repeatly
  = repeat_label

.hideble.repeat
  div
    = select_tag :period, options_for_select(["Каждый день", "Каждую неделю", "Каждый месяц"]), class: "form-control"
  br
  div
    = label_tag :max_date, "Повторять событие до:"
    = text_field_tag :max_date, l(@event.date), :class => "form-control for_date", :id => 'datetimepicker4'
br
div
  = f.submit "Сохранить событие", class: "btn btn-success btn-save_form btn-save_event", data: { "disable-with": "Сохраняю..." }

#help.col-sm-6

javascript:
  $(function () {
    $('.for_date').datetimepicker({
      locale: 'ru',
      format: 'DD-MM-YYYY',
      widgetPositioning: {
        vertical: 'bottom'
      }
    });
    $('.for_time').datetimepicker({
      locale: 'ru',
      format: 'HH:mm',
      stepping: 15,
      keepOpen: true,
      sideBySide: true
    });
    $('.hideble').hide();
  });

  document.body.addEventListener('ajax:complete', function(answer) {
    $("#event_form .modal-body").html(answer.detail[0].response);
  });

  $('label #repeatly').click(function(){
    $('.hideble.repeat').toggle();
  });

  $('#event_organizer_id').change(function(){
    if ($('#event_organizer_id option:selected').val() == "0")
      $('#new_organizer').show();
    else
      $('#new_organizer').hide();
  });

  $('#event_lector_id').change(function(){
    if ($('#event_lector_id option:selected').val() == "0")
      $('#new_lector').show();
    else
      $('#new_lector').hide();
  });

app/views/events/_modal_and_script.html.slim
#event_form.modal.fade role="dialog"
  .modal-dialog.form-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" &times;
        h4 class="modal-title"
      .modal-body
      .modal-footer
        button type="button" class="btn btn-success" =t('btn_save')
        button type="button" class="btn btn-default" data-dismiss="modal" =t('btn_cancel')

javascript:
  $(".my_event").click(function(){
    var url = "/events/"+$(this).attr("id")+"/edit";
    $.get(url, function(data){
      $("#event_form").modal();
      $("#event_form .modal-title").html("#{t('events.title_edit')}");
      $("#event_form .modal-body").html(data);
    });
  });
  $(".for_new").click(function(){
    var url = "/events/new";
    $.get(url, function(data){
      $("#event_form").modal();
      $("#event_form .modal-title").html("#{t('events.title_new')}");
      $("#event_form .modal-body").html(data);
    });
  });
  $(".btn-success").click(function(){
    $(".btn-save_event").click();
  })

app/views/events/_new.html.slim
= form_for :event, url: {action: "create"}, remote: true do |f|
  .row
    div.col-sm-6
      = f.label :room_id, t('events.room')
      = f.collection_select :room_id, @rooms, :id, :title, {}, class: "form-control"

  = render partial: 'events/form', locals: {f: f, repeat_label: t('events.form.repeat_label_for_new')}

app/views/events/new.html.slim
h2 Новое событие

= form_for :event, url: {action: "create"} do |f|

  = render partial: 'events/form', locals: {f: f}

app/views/events/personal.html.slim
= render 'button_group', current: @current, past: @past, canceled: @canceled

table.table.table-striped.table-bordered.datatable
  thead
    tr
      th scope="col"  &nbsp
      th scope="col"  =t('events.date')
      th scope="col"  =t('events.time')
      th scope="col"  =t('events.room')
      th scope="col"  =t('events.organizer')
      th scope="col"  =t('events.lector')
      th scope="col"  &nbsp
  tbody
    - @events.each do |event|
      tr
        td
          -if event.archive
            = event.title
          -else
            a.my_event id=event.id = event.title
        td
          = l(event.date)
        td
          = l(event.begin_time.localtime)
          = l(event.end_time.localtime, format: :dash)
        td
          = event.room.title
        td
          = event.organizer.name
        td
          = event.lector.name
        td
          =event.description

= render 'modal_and_script'