config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'events/personal', to: 'events#personal', as: :personal_current
  get 'events/personal/:state', to: 'events#personal', as: :personal
  resources :events, except: [:show]

  get 'rooms/admin_index', to: 'rooms#admin_index', as: :admin_index
  get 'rooms/print/:id', to: 'rooms#show_print', as: :print
  resources :rooms

  root to: 'rooms#index'
end

app/models/room.rb
class Room < ApplicationRecord
  include DateValidators
  include ActiveModel::Validations

  has_many :events, dependent: :destroy

  # проверка на присутствие
  validates :title, :begin_work_time, :end_work_time, presence: true

  validates_with RoomValidator

  def events_betweeb_date(begin_date,end_date,archive = false)
    self.events.where(date: (begin_date..end_date)).where(archive: archive).order(:date).order(:begin_time)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :user_is_admin, except: [:index, :show, :show_print]

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end

  def admin_index
    @rooms = Room.all
  end

  def show_print
    @begin_date = Date.parse(params[:begin_date])
    @end_date = Date.parse(params[:end_date])
    @room = Room.find(params[:id])
    @events = @room.events_betweeb_date @begin_date, @end_date
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@room.title} events", layout: false   # Excluding ".pdf" extension.
      end
    end
  end

  def new
    @room = Room.new(begin_work_time: Time.parse("9:00"), end_work_time: Time.parse("18:00"))
    respond_to do |format|
      format.html { render partial: 'new' }
    end
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to request.referrer }
      else
        format.html { render partial: 'new' }
      end
    end
  end

  def edit
    @room = Room.find(params[:id])
    respond_to do |format|
      format.html { render partial: 'edit' }
    end
  end

  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to request.referrer }
      else
        format.html { render partial: 'edit' }
      end
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    redirect_to rooms_path
  end

  def room_params
    params.require(:room).permit(:title, :description).merge(room_time_params)
  end

  private def room_time_params
    {
      begin_work_time: Time.parse(params.require(:room).permit(:begin_work_time)[:begin_work_time]),
      end_work_time: Time.parse(params.require(:room).permit(:end_work_time)[:end_work_time])
    }
  end
end

app/views/rooms/_edit.html.slim
= form_for :room, url: room_path(@room), method: :patch, remote: true  do |f|
  
  = render partial: 'rooms/form', locals: { f: f }

app/views/rooms/_form.html.slim
.row
  div.col-sm-12
    = f.label :title, t('rooms.form.title')
    = f.text_field :title, :class => "form-control"
br

.row
  div.col-sm-12
    = f.label :description, t('rooms.form.description')
    = f.text_area :description, :class => "form-control"
br

.row
  div.col-sm-6
    = f.label :begin_work_time, t('rooms.form.begin_work_time')
    = f.text_field :begin_work_time, value: l(@room.begin_work_time.localtime), :class => "form-control for_time", id: "datetimepicker1"
  div.col-sm-6
    = f.label :end_work_time, t('rooms.form.end_work_time')
    = f.text_field :end_work_time, value: l(@room.end_work_time.localtime), :class => "form-control for_time", id: "datetimepicker2"
br

p
  = f.submit "Сохранить", class: "btn btn-success btn-save_form btn-save_room"

javascript:
  $(function () {
    $('.for_time').datetimepicker({
      locale: 'ru',
      format: 'HH:mm',
      stepping: 15,
      keepOpen: true,
      sideBySide: true
    });
  });
  document.body.addEventListener('ajax:complete', function(answer) {
    $("#room_form .modal-body").html(answer.detail[0].response);
  });

app/views/rooms/_modal_and_script.html.slim
#room_form.modal.fade role="dialog"
  .modal-dialog.form-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" &times;
        h4 class="modal-title"
      .modal-body
      .modal-footer
        button type="button" class="btn btn-success" =t('btn_save')
        button type="button" class="btn btn-default" data-dismiss="modal" =t('btn_cancel')

javascript:
  $(".room").click(function(){
    var url = "/rooms/"+$(this).attr("id")+"/edit";
    $.get(url, function(data){
      $("#room_form").modal();
      $("#room_form .modal-title").html("#{t('rooms.title_edit')}");
      $("#room_form .modal-body").html(data);
    });
  });
  $(".for_new").click(function(){
    var url = "/rooms/new";
    $.get(url, function(data){
      $("#room_form").modal();
      $("#room_form .modal-title").html("#{t('rooms.title_new')}");
      $("#room_form .modal-body").html(data);
    });
  });
  $(".btn-success").click(function(){
    $(".btn-save_room").click();
  })

app/views/rooms/_new.html.slim
= form_for :room, url: {action: "create"}, remote: true  do |f|
  
  = render partial: 'rooms/form', locals: { f: f }

app/views/rooms/admin_index.html.slim
.btn.btn-margins.btn-info.btn-margins.for_new style="float: right;" =t('rooms.btn_create')
br
br
table.table.table-striped.table-bordered.datatable
  thead
    tr
      th scope="col"  &nbsp
      th scope="col"  =t('rooms.time')
      th scope="col"  &nbsp
  tbody
    - @rooms.each do |room|
      tr
        td
          a.room id=room.id = room.title
        td
          = l(room.begin_work_time.localtime)
          = l(room.end_work_time.localtime, format: :dash)
        td
          = room.description
= render 'modal_and_script'

app/views/rooms/index.html.slim
.cards
  .row
    - @rooms.each_slice(3).each do |rooms_slice|
      - rooms_slice.each do |room|
        .col-sm-6.col-md-4.room-block
          .well
            - if user_signed_in? and current_user.role == "admin" 
              a.btn.btn-xs.btn-danger.btn-margins.room_deleter href=room_path(room) data-method="delete" data-confirm="Внимание! Вы удаляете комнату!"
                = t('rooms.btn_delete')
            = link_to room_path(room) do
              .card-body
                h4 = room.title
                .card-text
                  = room.description
              .card-footer
                = t('rooms.time')
                = l(room.begin_work_time.localtime)
                = l(room.end_work_time.localtime, format: :dash)        

app/views/rooms/show.html.slim
h2
  = @room.title
p.description
  = @room.description
=t('rooms.time')
= l(@room.begin_work_time.localtime, format: :from)
= l(@room.end_work_time.localtime, format: :to)
.btn.btn-margins.btn-info.btn-margins.for_print =t('rooms.btn_for_print')
hr

br

-if user_signed_in?
  #calendar data-room-id="#{@room.id}" current_user = current_user.id
-else
  #calendar data-room-id="#{@room.id}"

#event_form.modal.fade role="dialog"
  .modal-dialog.form-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" &times;
        h4 class="modal-title"
      .modal-body
      .modal-footer
        button type="button" class="btn btn-success" =t('btn_save')
        button type="button" class="btn btn-default" data-dismiss="modal" =t('btn_cancel')

javascript:
  $(function () {
    $('.for_date').datetimepicker({
      locale: 'ru',
      format: 'YYYY-MM-DD',
      widgetPositioning: {
        vertical: 'bottom'
      }
    });
  });
  $(".for_print").click(function(){
    var date = $("#calendar").fullCalendar('getDate');
    var begin_date = date.format('YYYY-MM-DD');
    var end_date = date.endOf('month').format('YYYY-MM-DD');
    var room = $('#calendar').attr('data-room-id');
    window.open("/rooms/print/"+room+".pdf?begin_date="+begin_date+"&end_date="+end_date)
  });
  $(".btn-success").click(function(){
    $(".btn-save_event").click();
  })

app/views/rooms/show_print.pdf.slim
doctype html
html
  head
    title
      =t('title')
    meta charset="UTF-8"
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    = wicked_pdf_stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  body
    h2
      = @room.title
    hr

    =t('rooms.time')
    = l(@room.begin_work_time.localtime, format: :from)
    = l(@room.end_work_time.localtime, format: :to)

    p.description
      = @room.description

    h3
      =t('rooms.period')
      | с #{l(@begin_date)} по #{l(@end_date)}

    table.table.table-bordered
      tr
        th №
        th =t('events.date')
        th =t('events.time')
        th =t('events.title')
      - @events.each_with_index do |event, i|
        tr.nobreak
          td
            = i+1
          td
            = l(event.date)
          td
            = l(event.begin_time.localtime)
            = l(event.end_time.localtime, format: :dash)
          td
            b
              = event.title
            br
            =t('events.lector')
            |: #{event.lector.name}
            br
            =t('events.organizer')
            |: #{event.organizer.name}
            br
            i
              = event.description